(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen');
const show=id=>screens.forEach(s=>s.classList.toggle('active',s.id===id));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const state={name:'',age:18,under18:false,difficulty:'easy',mood:'tropical',bar:'tropical',phase:'start',drink:null,step:0,correct:0,wrong:0,points:0,startedAt:0,serving:null,questionFails:0,amountFails:0,conversationIndex:0,conversationAnswers:{},sensorOK:false,action:null,afterAction:null,shakeProgress:0,muddleProgress:0,drinkProgress:0,lastMotion:0,lastMuddle:0,baselineBeta:null,baselineGamma:null,waitingPortrait:false,waitingLandscape:false,returning:false,idleTimer:null};

const drinks=[
{id:'mojito',name:'Mojito',minAge:18,alcoholic:true,intro:'Mojito! Friskt och klassiskt.',steps:[
{q:'Vilken bassprit börjar vi med?',a:'Vit rom',opts:['Vit rom','Gin','Tequila'],amount:{base:4,unit:'cl',label:'vit rom'}},
{q:'Vilken citrus ska i?',a:'Lime',opts:['Lime','Citron','Apelsin'],amount:{base:2,unit:'cl',label:'limejuice'}},
{q:'Vilken ört hör hemma i en Mojito?',a:'Mynta',opts:['Mynta','Basilika','Rosmarin'],amount:{base:8,unit:'blad',label:'mynta'}},
{q:'Vad använder vi för sötma?',a:'Socker',opts:['Socker','Salt','Kaffe'],amount:{base:2,unit:'tsk',label:'socker'}},
{q:'Hur behandlar vi lime och mynta först?',a:'Muddla försiktigt',opts:['Muddla försiktigt','Koka','Mixa hårt'],action:'muddle'},
{q:'Nu ska allt kylas och blandas. Vad gör vi?',a:'Skaka',opts:['Skaka','Värm','Låt stå'],action:'shake'},
{q:'Vilket glas passar bäst?',a:'Highballglas',opts:['Highballglas','Martiniglas','Shotglas']},
{q:'Vad toppar vi med?',a:'Sodavatten',opts:['Sodavatten','Mjölk','Cola'],amount:{base:4,unit:'cl',label:'sodavatten'}},
{q:'Sista detaljen: vad dekorerar vi med?',a:'Lime och mynta',opts:['Lime och mynta','Oliv','Kanelstång']}]},
{id:'margarita',name:'Margarita',minAge:18,alcoholic:true,intro:'Margarita. Då håller vi koll på syra, sötma och salt.',steps:[
{q:'Vilken bassprit börjar vi med?',a:'Tequila',opts:['Tequila','Vodka','Whisky'],amount:{base:4,unit:'cl',label:'tequila'}},{q:'Vilken citrus ska i?',a:'Lime',opts:['Lime','Citron','Grapefrukt'],amount:{base:2,unit:'cl',label:'limejuice'}},{q:'Vilken apelsinlikör används ofta?',a:'Triple sec',opts:['Triple sec','Amaretto','Kahlúa'],amount:{base:2,unit:'cl',label:'triple sec'}},{q:'Vad gör vi med glaskanten?',a:'Saltkant',opts:['Saltkant','Sockerkant','Ingen kant']},{q:'Nu ska den kylas ordentligt.',a:'Skaka',opts:['Skaka','Värm','Rör med sugrör'],action:'shake'},{q:'Vilket glas är rätt?',a:'Margaritaglas',opts:['Margaritaglas','Ölsejdel','Shotglas']},{q:'Vilken garnish passar?',a:'Limeklyfta',opts:['Limeklyfta','Oliv','Myntabukett']}]},
{id:'manhattan',name:'Manhattan',minAge:18,alcoholic:true,intro:'Manhattan. Nu går vi åt det klassiska hållet.',steps:[
{q:'Vilken bassprit är grunden?',a:'Whisky',opts:['Whisky','Rom','Gin'],amount:{base:4,unit:'cl',label:'whisky'}},{q:'Vilken förstärkt vin-ingrediens används?',a:'Söt vermouth',opts:['Söt vermouth','Torr cider','Porter'],amount:{base:2,unit:'cl',label:'söt vermouth'}},{q:'Vilken bitter används ofta?',a:'Angostura bitters',opts:['Angostura bitters','Tonic','Grenadin'],amount:{base:2,unit:'stänk',label:'Angostura bitters'}},{q:'Hur blandar vi en klassisk Manhattan?',a:'Rör med is',opts:['Rör med is','Skaka hårt','Mixa']},{q:'Vilket glas serveras den i?',a:'Cocktailglas',opts:['Cocktailglas','Highballglas','Ölglas']},{q:'Vilken garnish passar?',a:'Cocktailkörsbär',opts:['Cocktailkörsbär','Selleri','Gurka']}]},
{id:'virgin_mojito',name:'Virgin Mojito',minAge:0,alcoholic:false,intro:'Virgin Mojito! Friskt och helt alkoholfritt.',steps:[
{q:'Vilken citrus börjar vi med?',a:'Lime',opts:['Lime','Citron','Apelsin'],amount:{base:2,unit:'cl',label:'limejuice'}},{q:'Vilken ört använder vi?',a:'Mynta',opts:['Mynta','Timjan','Dill'],amount:{base:8,unit:'blad',label:'mynta'}},{q:'Vad använder vi för sötma?',a:'Sockerlag',opts:['Sockerlag','Saltlag','Kaffe'],amount:{base:2,unit:'cl',label:'sockerlag'}},{q:'Hur behandlar vi lime och mynta?',a:'Muddla försiktigt',opts:['Muddla försiktigt','Koka','Mosa till puré'],action:'muddle'},{q:'Nu ska den kylas och blandas.',a:'Skaka',opts:['Skaka','Värm','Låt stå'],action:'shake'},{q:'Vad toppar vi med?',a:'Sodavatten',opts:['Sodavatten','Mjölk','Tomatjuice'],amount:{base:8,unit:'cl',label:'sodavatten'}},{q:'Vilket glas?',a:'Highballglas',opts:['Highballglas','Shotglas','Champagneflöjt']}]},
{id:'shirley',name:'Shirley Temple',minAge:0,alcoholic:false,intro:'Shirley Temple – festlig, söt och alkoholfri.',steps:[
{q:'Vilken bas använder vi?',a:'Ginger ale',opts:['Ginger ale','Espresso','Tonic'],amount:{base:12,unit:'cl',label:'ginger ale'}},{q:'Vilken söt röd ingrediens ska i?',a:'Grenadin',opts:['Grenadin','Soja','Bitters'],amount:{base:2,unit:'cl',label:'grenadin'}},{q:'Vilken citrus passar?',a:'Lime eller citron',opts:['Lime eller citron','Tomat','Gurka'],amount:{base:1,unit:'cl',label:'citrusjuice'}},{q:'Vilket glas passar?',a:'Highballglas',opts:['Highballglas','Shotglas','Whiskyglas']},{q:'Vad kan vi dekorera med?',a:'Körsbär',opts:['Körsbär','Oliv','Rosmarin']}]},
{id:'tropical_cooler',name:'Tropical Cooler',minAge:0,alcoholic:false,intro:'Tropical Cooler. Fruktigt och friskt.',steps:[
{q:'Vilken juice ger tropisk bas?',a:'Ananasjuice',opts:['Ananasjuice','Tomatjuice','Kaffe'],amount:{base:6,unit:'cl',label:'ananasjuice'}},{q:'Vilken citrus ger syra?',a:'Lime',opts:['Lime','Rödbeta','Vanilj'],amount:{base:2,unit:'cl',label:'limejuice'}},{q:'Vilken andra juice passar?',a:'Apelsinjuice',opts:['Apelsinjuice','Mjölk','Soja'],amount:{base:6,unit:'cl',label:'apelsinjuice'}},{q:'Nu kyler vi ordentligt.',a:'Skaka',opts:['Skaka','Värm','Låt stå'],action:'shake'},{q:'Vilket glas?',a:'Highballglas',opts:['Highballglas','Shotglas','Espressokopp']},{q:'Vilken garnish?',a:'Apelsin eller lime',opts:['Apelsin eller lime','Oliv','Kanelstång']}]}
];
const moodToBar={party:'rooftop',tropical:'tropical',classic:'manhattan',elegant:'hotel'};
const moodLines={party:'Festligt? Då behöver vi lite mer puls. Häng med!',tropical:'Tropiskt? Då ska vi ha sol, palmer och bambu. Följ med!',classic:'Lugnt och klassiskt. Då känner jag precis rätt ställe på Manhattan.',elegant:'Elegant och exklusivt. Då flyttar vi oss till en finare hotellbar.',surprise:'Överraska dig? Det är farligt att säga till en bartender. Nu kör vi.'};
const convo=[
{key:'how',q:n=>`Så ${n}, hur är läget med dig idag?`},
{key:'day',q:()=>`Hur har dagen varit hittills?`},
{key:'from',q:()=>`Var kommer du ifrån?`},
{key:'work',q:()=>`Vad brukar du göra om dagarna?`},
{key:'plans',q:()=>`Och vad händer efter det här – lugn kväll eller något mer på gång?`}
];

function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9,. ]/g,' ').replace(/\s+/g,' ').trim().replace(/whiskey/g,'whisky').replace(/high ball/g,'highball').replace(/soda vatten/g,'sodavatten').replace(/trippel sek|trippelsek/g,'triple sec')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function stopSpeech(){try{speechSynthesis.cancel()}catch(e){}}
function speak(text,onEnd){try{if(!('speechSynthesis'in window)){if(onEnd)setTimeout(onEnd,Math.min(4500,900+text.length*38));return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='sv-SE';u.rate=.96;u.pitch=.96;if(onEnd){let done=false;const finish=()=>{if(done)return;done=true;onEnd()};u.onend=finish;u.onerror=finish;setTimeout(finish,Math.max(2200,Math.min(8500,900+text.length*55)))}speechSynthesis.speak(u)}catch(e){if(onEnd)setTimeout(onEnd,1200)}}
function stopIdle(){clearTimeout(state.idleTimer);state.idleTimer=null}
function scheduleIdle(){stopIdle();if(state.phase!=='chat')return;state.idleTimer=setTimeout(()=>{const lines=['Ingen brådska. Jag står kvar här.','Det är rätt lugnt i baren just nu.','Du får gärna fråga mig något också – det är ju så barsnack funkar.','Och blir du törstig mitt i samtalet är det bara att beställa.'];const line=lines[Math.floor(Math.random()*lines.length)];$('#dialogText').textContent=line;speak(line,()=>renderConversationInput())},9000+Math.random()*3500)}
function tryOrientation(mode,fullscreen=false){try{screen.orientation?.unlock?.()}catch(e){}const doLock=()=>{try{const p=screen.orientation?.lock?.(mode);if(p&&p.catch)p.catch(()=>{})}catch(e){}};if(fullscreen){try{if(document.fullscreenElement)doLock();else if(document.documentElement.requestFullscreen){const p=document.documentElement.requestFullscreen();if(p&&p.then)p.then(doLock).catch(()=>{});else doLock()}else doLock()}catch(e){doLock()}}else doLock()}
const isPortrait=()=>matchMedia('(orientation: portrait)').matches,isLandscape=()=>matchMedia('(orientation: landscape)').matches;
function updateOrientationBanner(){const b=$('#orientationBanner');if(b)b.style.display=isPortrait()?'flex':'none'}
async function requestSensors(){let ok=true;try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function')ok=(await DeviceMotionEvent.requestPermission())==='granted'&&ok;if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function')ok=(await DeviceOrientationEvent.requestPermission())==='granted'&&ok}catch(e){ok=false}state.sensorOK=ok;toast(ok?'Sensorer aktiverade.':'Sensorer kunde inte aktiveras – reservknappar finns.');return ok}
function makeBottles(){const labels=['ROM','GIN','TEQ','WHISKY','VERM','SEC','BITTER','SIRAP','JUICE','SODA'],colors=['#eee8d8','#72a67f','#c89a55','#82502f','#ad4b43','#edb06e','#49302b','#d64d68','#e8a346','#9bdde5'];$('#bottles').innerHTML=labels.map((x,i)=>`<div class="bottle" data-label="${x}" style="background:${colors[i]}"></div>`).join('')}
function barName(b){return({tropical:'strandbar',manhattan:'Manhattan-bar',rooftop:'rooftop-bar',hotel:'hotellbar'})[b]||'bar'}
function diffLabel(){return state.difficulty==='easy'?'Lätt':state.difficulty==='medium'?'Medel':'Svår'}
function updateHud(){const serv=state.difficulty==='hard'&&state.serving&&state.drink?.alcoholic?` · ${state.serving}:a`:'';$('#hudPlayer').textContent=`${state.name} · ${state.under18?'alkoholfritt':'18+'} · ${diffLabel()}${serv}`;$('#hudDrink').textContent=state.drink?state.drink.name:'Ingen beställning ännu'}

$$('.difficultyBtn').forEach(btn=>btn.onclick=()=>{state.difficulty=btn.dataset.difficulty;$$('.difficultyBtn').forEach(b=>b.classList.toggle('selected',b===btn));$('#difficultyHelp').textContent=state.difficulty==='easy'?'Lätt: välj mellan tre alternativ eller säg svaret.':state.difficulty==='medium'?'Medel: skriv eller säg svaret själv. Efter tre fel får du tre tips.':'Svår: samma som Medel, plus mängder och proportioner. Efter tre fel får du tre tips.'});
$('#sensorBtn').onclick=requestSensors;
$('#enterBtn').onclick=()=>{const name=$('#nameInput').value.trim(),age=Number($('#ageInput').value);if(!name||!age||age<1||age>120){$('#startError').textContent='Fyll i namn och en rimlig ålder.';return}state.name=name;state.age=age;state.under18=age<18;state.phase='mood';$('#startError').textContent='';$('#moodHello').textContent=`Hej ${name}! Välkommen.`;$('#moodPrompt').textContent=state.under18?'Vilket mood är du på idag? Jag håller baren helt alkoholfri.':'Vilket mood är du på idag?';show('moodScreen');speak(`Hej ${name}! Välkommen. Vilket mood är du på idag?`)};
$$('.mood').forEach(btn=>btn.onclick=()=>selectMood(btn.dataset.mood));
function selectMood(mood){if(state.phase!=='mood')return;state.phase='chat';state.mood=mood;state.bar=mood==='surprise'?['tropical','manhattan','rooftop','hotel'][Math.floor(Math.random()*4)]:moodToBar[mood];$$('.mood').forEach(b=>b.disabled=true);speak(moodLines[mood]);enterBar();tryOrientation('landscape',true);setTimeout(()=>$$('.mood').forEach(b=>b.disabled=false),1200)}
function enterBar(){stopIdle();makeBottles();$('#barScene').className=state.bar;state.conversationIndex=0;state.conversationAnswers={};state.drink=null;state.serving=null;updateHud();show('barScreen');updateOrientationBanner();const intro=`Välkommen till min ${barName(state.bar)}, ${state.name}. Slå dig ner.`;$('#dialogText').textContent=intro;$('#dialogControls').innerHTML='';speak(intro,()=>renderConversationInput());scheduleIdle()}
function renderConversationInput(){if(state.phase!=='chat')return;const q=convo[Math.min(state.conversationIndex,convo.length-1)]?.q(state.name)||'Vad är du sugen på?';if(state.conversationIndex<convo.length){$('#dialogText').textContent=q;speak(q)}else{const t='Vad känner du för nu då? Säg bara till när du är sugen på något.';$('#dialogText').textContent=t;speak(t)}$('#dialogControls').innerHTML=`<div class="inputRow"><input id="chatInput" placeholder="Svara, fråga bartendern eller beställ en drink"><button class="btn" id="chatSendBtn">Säg</button><button class="btn secondary" id="chatMicBtn">🎙️</button></div><div class="small">Du kan till exempel säga: “Bra, hur är läget med dig?” eller “Jag vill ha en Mojito.”</div>`;$('#chatSendBtn').onclick=()=>handleConversation($('#chatInput').value);$('#chatInput').onkeydown=e=>{if(e.key==='Enter')handleConversation(e.target.value)};$('#chatMicBtn').onclick=()=>recognize(alts=>handleConversation(alts[0]||''),$('#chatMicBtn'));scheduleIdle()}
function resolveDrink(q){const x=normalize(q),aliases={'mojito':'mojito','mohito':'mojito','margarita':'margarita','manhattan':'manhattan','virgin mojito':'virgin_mojito','alkoholfri mojito':'virgin_mojito','mocktail mojito':'virgin_mojito','shirley temple':'shirley','tropical cooler':'tropical_cooler','tropisk drink':'tropical_cooler'};let id=aliases[x];if(!id){for(const [k,v] of Object.entries(aliases)){if(x.includes(k)){id=v;break}}}return drinks.find(d=>d.id===id)}
function answerBartenderQuestion(x){if(/hur ar laget med dig|hur mar du|sjalv da|och du|hur har du det/.test(x))return 'Med mig är det bra, tack. Lagom mycket folk, bra musik och än så länge har ingen tappat ett glas. Då ska man inte klaga.';if(/har du haft en bra dag|hur har din dag varit/.test(x))return 'Jodå, faktiskt. En ganska bra dag. Lite stressigt en stund, men det hör nästan till bakom en bardisk.';if(/var kommer du ifran|var ar du ifran/.test(x))return 'Jag brukar säga att jag kommer från den här sidan av bardisken. Men jag har jobbat på några olika ställen och plockat upp lite av varje.';if(/vad gor du|vad jobbar du med/.test(x))return 'Just nu försöker jag hålla koll på flaskor, is, gäster och dig samtidigt. Det är ungefär bartenderjobbet i ett nötskal.';return ''}
function naturalReply(text){const x=normalize(text);let parts=[];if(/bra|fint|toppen|kanon|perfekt|helt okej/.test(x))parts.push('Skönt att höra.');else if(/daligt|jobbigt|trott|stress|sliten|inte bra/.test(x))parts.push('Då får vi hoppas att den här stunden blir lite lugnare.');else if(/jobbar|arbete|jobb/.test(x))parts.push('Ja, då är det rätt skönt att lämna jobbet utanför dörren en stund.');else if(/pension/.test(x))parts.push('Det låter ändå som att du kan styra lite mer över din egen tid.');else if(/studer|pluggar|skola/.test(x))parts.push('Då har du säkert fullt upp redan innan du kommer hit.');else parts.push('Jag fattar.');const back=answerBartenderQuestion(x);if(back)parts.push(back);return parts.join(' ')}
function handleConversation(raw){stopIdle();const text=String(raw||'').trim();if(!text){toast('Säg eller skriv något först.');return}const drink=resolveDrink(text);if(drink){orderDrink(drink);return}const idx=Math.min(state.conversationIndex,convo.length-1),item=convo[idx];if(item&&state.conversationIndex<convo.length)state.conversationAnswers[item.key]=text;const reply=naturalReply(text);state.conversationIndex++;$('#dialogControls').innerHTML='';$('#dialogText').textContent=reply;speak(reply,()=>{if(state.phase!=='chat')return;if(state.conversationIndex===2){const n='Förresten, om du redan vet vad du vill ha så är det bara att säga det. Annars snackar vi vidare.';$('#dialogText').textContent=n;speak(n,()=>renderConversationInput())}else if(state.conversationIndex>=convo.length){const n='Kul att snacka. Vad vill du ha då?';$('#dialogText').textContent=n;speak(n,()=>renderConversationInput())}else renderConversationInput()})}
function orderDrink(d){stopIdle();if(state.under18&&d.minAge>=18){const t='Den innehåller alkohol. Jag kan göra en Virgin Mojito, Shirley Temple eller Tropical Cooler istället.';$('#dialogText').textContent=t;speak(t,()=>renderConversationInput());return}state.phase='recipe';state.drink=d;state.step=0;state.correct=0;state.wrong=0;state.points=0;state.startedAt=Date.now();state.serving=null;state.questionFails=0;state.amountFails=0;updateHud();$('#dialogControls').innerHTML='';const intro=`${d.intro} Bra val. Du får hjälpa mig bakom baren.`;$('#dialogText').textContent=intro;speak(intro,()=>{if(state.difficulty==='hard')askServing();else renderStep()})}
function parseNum(text){const x=normalize(text).replace(',','.');const words={en:1,ett:1,tva:2,tre:3,fyra:4,fyran:4,fem:5,sex:6,sexa:6,sexan:6,sju:7,atta:8,attan:8,nio:9,tio:10,tolv:12,sexton:16};for(const [w,n] of Object.entries(words))if(x===w||x.includes(w))return n;const m=x.match(/\d+(?:\.\d+)?/);return m?Number(m[0]):NaN}
function askServing(){const d=state.drink,text=d.alcoholic?`${d.name}. På svår nivå: vill du göra en fyra, sexa eller åtta?`:`${d.name}. På svår nivå: vill du göra en liten, mellan eller stor?`;showPrompt('Bartendern',text,d.alcoholic?'4, 6 eller 8':'liten, mellan eller stor',(value,status,wrap)=>{let n;if(!d.alcoholic){const x=normalize(value);if(x.includes('liten'))n=4;else if(x.includes('mellan'))n=6;else if(x.includes('stor'))n=8}if(!n)n=parseNum(value);if(![4,6,8].includes(n)){status.textContent=d.alcoholic?'Svara 4, 6 eller 8.':'Svara liten, mellan eller stor.';return}state.serving=n;updateHud();wrap.remove();const r=d.alcoholic?`${n}:a. Då skalar vi receptet efter den.`:`Bra, då kör vi ${n===4?'liten':n===6?'mellan':'stor'}.`;$('#dialogText').textContent=r;speak(r,renderStep)})}
function showPrompt(title,text,placeholder,onSubmit){document.querySelector('.hardPromptOverlay')?.remove();const wrap=document.createElement('div');wrap.className='hardPromptOverlay';wrap.innerHTML=`<div class="hardPromptCard"><h3>${title}</h3><p>${text}</p><div class="hardPromptRow"><input id="hardPromptInput" placeholder="${placeholder}"><button class="btn" id="hardPromptSend">Svara</button><button class="btn secondary" id="hardPromptMic">🎙️</button></div><div id="hardPromptStatus" class="hardPromptStatus"></div><div id="amountHints"></div></div>`;document.body.appendChild(wrap);const input=$('#hardPromptInput'),send=$('#hardPromptSend'),mic=$('#hardPromptMic'),status=$('#hardPromptStatus');send.onclick=()=>onSubmit(input.value,status,wrap);input.onkeydown=e=>{if(e.key==='Enter')onSubmit(input.value,status,wrap)};mic.onclick=()=>recognize(alts=>{input.value=alts[0]||'';onSubmit(input.value,status,wrap)},mic,status);speak(text);setTimeout(()=>input.focus(),120);return wrap}
function renderStep(){if(state.step>=state.drink.steps.length){startPhysicalAction('drink','result');return}state.questionFails=0;state.amountFails=0;const s=state.drink.steps[state.step];$('#dialogText').textContent=s.q;speak(s.q);if(state.difficulty==='easy'){renderEasy(s)}else renderFree(s)}
function renderEasy(s){$('#dialogControls').innerHTML=`<div class="choices">${s.opts.map(o=>`<button class="choice">${o}</button>`).join('')}</div><div class="freeAnswerRow"><button class="btn secondary" id="recipeMic">🎙️ Säg svaret</button><span class="freeAnswerStatus">Tryck eller prata.</span></div>`;$$('.choice').forEach(b=>b.onclick=()=>answerStep(b.textContent,b));$('#recipeMic').onclick=()=>recognize(alts=>{const match=bestOption(alts[0]||'',s.opts);if(match){const b=$$('.choice').find(x=>x.textContent===match);answerStep(match,b)}else toast('Jag kunde inte koppla det till något svar.')},$('#recipeMic'))}
function renderFree(s,message=''){const hint=state.questionFails>=3?`<div class="hintTitle">Tre försök – här får du tre tips. Ett är rätt.</div><div class="choices">${s.opts.map(o=>`<button class="choice">${o}</button>`).join('')}</div>`:'';$('#dialogControls').innerHTML=`<div class="freeAnswerRow"><input id="freeAnswer" placeholder="Skriv svaret själv"><button class="btn" id="freeSend">Svara</button><button class="btn secondary" id="freeMic">🎙️</button><div class="freeAnswerStatus">${message||'Inga svarsalternativ visas.'}</div></div>${hint}`;$('#freeSend').onclick=()=>submitFree($('#freeAnswer').value);$('#freeAnswer').onkeydown=e=>{if(e.key==='Enter')submitFree(e.target.value)};$('#freeMic').onclick=()=>recognize(alts=>{const v=alts[0]||'';$('#freeAnswer').value=v;submitFree(v)},$('#freeMic'));$$('.choice').forEach(b=>b.onclick=()=>answerStep(b.textContent,b));setTimeout(()=>$('#freeAnswer')?.focus(),80)}
function spokenAlias(text){let x=normalize(text);const map=[[/^rom$/,'vit rom'],[/^soda$/,'sodavatten'],[/^highball$/,'highballglas'],[/^martini$/,'martiniglas'],[/^cocktail$/,'cocktailglas'],[/^salt$/,'saltkant'],[/^muddla$/,'muddla forsiktigt'],[/^ror$|^rora$/,'ror med is']];for(const [r,v]of map)if(r.test(x))return v;return x}
function scoreMatch(a,b){const h=spokenAlias(a),o=normalize(b);if(!h||!o)return 0;if(h===o)return 100;if(o.includes(h)||h.includes(o))return 90;const hs=new Set(h.split(' ')),os=new Set(o.split(' '));let c=0;hs.forEach(t=>{if(os.has(t))c++});return c?70*c/Math.max(1,Math.min(hs.size,os.size)):0}
function bestOption(text,opts){let best=null,score=0;for(const o of opts){const s=scoreMatch(text,o);if(s>score){score=s;best=o}}return score>=55?best:null}
function submitFree(text){const s=state.drink.steps[state.step],match=bestOption(text,s.opts);if(match&&normalize(match)===normalize(s.a)){answerStep(match,null);return}state.wrong++;state.points=Math.max(0,state.points-2);state.questionFails++;const msg=state.questionFails>=3?'Inte riktigt. Nu får du tre tips nedan – ett är rätt.':`Inte riktigt. Försök igen. (${state.questionFails}/3)`;$('#dialogText').textContent=msg;speak(msg,()=>renderFree(s,msg))}
async function answerStep(answer,btn){const s=state.drink.steps[state.step];if(normalize(answer)!==normalize(s.a)){state.wrong++;state.points=Math.max(0,state.points-2);if(btn)btn.classList.add('bad');if(state.difficulty==='easy'){const t='Inte riktigt. Försök igen.';$('#dialogText').textContent=t;speak(t,()=>renderEasy(s))}else{state.questionFails++;const t=state.questionFails>=3?'Inte riktigt. Här får du tre tips – ett är rätt.':'Inte riktigt. Försök igen.';$('#dialogText').textContent=t;speak(t,()=>renderFree(s,t))}return}state.correct++;state.points+=10;if(btn)btn.classList.add('good');if(state.difficulty==='hard'&&s.amount){askAmount(s);return}const praise=['Precis.','Rätt.','Snyggt.','Där satt den.','Bra, du börjar få bartenderkoll.'][Math.floor(Math.random()*5)];$('#dialogText').textContent=praise;speak(praise,()=>advanceStep(s))}
function expectedAmount(s){return s.amount.base*((state.serving||4)/4)}
function fmt(n,u){const v=Number.isInteger(n)?String(n):String(Math.round(n*10)/10).replace('.',',');return `${v} ${u}`}
function askAmount(s){state.amountFails=0;const expected=expectedAmount(s),size=state.drink.alcoholic?`${state.serving}:an`:state.serving===4?'den lilla':state.serving===6?'mellanstorleken':'den stora';const q=`Bra, ${s.a}. Hur mycket ${s.amount.label} ska vi ha till ${size}?`;showPrompt('Bartendern',q,`Mängd i ${s.amount.unit}`,(value,status,wrap)=>{const n=parseNum(value);if(Number.isFinite(n)&&Math.abs(n-expected)<.11){status.textContent=`Rätt: ${fmt(expected,s.amount.unit)}.`;speak(`Precis. ${fmt(expected,s.amount.unit)}.`,()=>{wrap.remove();advanceStep(s)});return}state.wrong++;state.points=Math.max(0,state.points-2);state.amountFails++;status.textContent=state.amountFails>=3?'Tre fel. Här får du tre tips – ett är rätt.':`Inte riktigt. Försök igen. (${state.amountFails}/3)`;speak('Inte riktigt. Tänk på proportionerna.');if(state.amountFails>=3)renderAmountHints(expected,s.amount.unit,status,wrap,s)})}
function renderAmountHints(expected,unit,status,wrap,s){const box=wrap.querySelector('#amountHints');if(!box||box.children.length)return;const vals=[expected,Math.max(.5,expected*.5),expected*1.5].map(n=>Math.round(n*10)/10).sort(()=>Math.random()-.5);box.innerHTML=`<div class="hintTitle">Tre tips – ett är rätt.</div><div class="amountHints">${vals.map(v=>`<button class="choice" data-v="${v}">${fmt(v,unit)}</button>`).join('')}</div>`;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.v);if(Math.abs(v-expected)<.11){b.classList.add('good');status.textContent='Rätt.';speak(`Precis. ${fmt(expected,unit)}.`,()=>{wrap.remove();advanceStep(s)})}else{b.classList.add('bad');state.wrong++;state.points=Math.max(0,state.points-2);status.textContent='Inte den. Ett av de andra två är rätt.'}})}
function advanceStep(s){state.step++;state.questionFails=0;state.amountFails=0;if(s.action)startPhysicalAction(s.action,'continue');else renderStep()}
function startPhysicalAction(type,afterAction){state.phase='action';stopIdle();state.action=type;state.afterAction=afterAction;state.waitingPortrait=true;state.waitingLandscape=false;state.returning=false;state.shakeProgress=0;state.muddleProgress=0;state.drinkProgress=0;state.baselineBeta=null;state.baselineGamma=null;show('actionScreen');['muddleStage','shakeStage','drinkStage','returnStage'].forEach(id=>$('#'+id).classList.add('hidden'));$('#rotateStage').classList.remove('hidden');const names={muddle:'Nu ska du muddla myntan',shake:'Nu blir telefonen en shaker',drink:'Nu blir telefonen glaset'};$('#rotateTitle').textContent=names[type];$('#rotateHint').textContent='Det här momentet görs i stående läge.';speak(`${names[type]}. Vrid telefonen till stående.`);if(isPortrait())showPhysicalStage()}
$('#startPortraitBtn').onclick=async()=>{await requestSensors();tryOrientation('portrait',true);if(isPortrait())showPhysicalStage();else toast('Vrid telefonen till stående. Spelet fortsätter automatiskt.')};
function showPhysicalStage(){if(!$('#actionScreen').classList.contains('active'))return;state.waitingPortrait=false;$('#rotateStage').classList.add('hidden');['muddleStage','shakeStage','drinkStage','returnStage'].forEach(id=>$('#'+id).classList.add('hidden'));if(state.action==='muddle'){$('#muddleStage').classList.remove('hidden');updateMuddle();speak('Tryck och gnugga myntan och limen försiktigt med fingret.')}else if(state.action==='shake'){$('#shakeStage').classList.remove('hidden');updateShake();speak('Skaka ordentligt!')}else{$('#drinkStage').classList.remove('hidden');updateDrink();speak('Lyft telefonen mot munnen och luta den för att smaka.')}}
function finishPhysical(label){['muddleStage','shakeStage','drinkStage'].forEach(id=>$('#'+id).classList.add('hidden'));$('#returnStage').classList.remove('hidden');state.waitingLandscape=true;$('#returnText').textContent=label+' Vrid tillbaka telefonen vågrätt. Spelet fortsätter automatiskt när landscape upptäcks.';speak(label+' Nu går vi tillbaka till baren.');tryOrientation('landscape',false);setTimeout(()=>{if(isLandscape())finalizeLandscapeReturn()},350)}
function finalizeLandscapeReturn(force=false){if((!state.waitingLandscape&&!force)||state.returning)return;state.returning=true;state.waitingLandscape=false;if(state.afterAction==='result'){state.phase='result';showResult()}else{state.phase='recipe';show('barScreen');updateOrientationBanner();renderStep()}state.returning=false}
$('#returnBarBtn').onclick=()=>{tryOrientation('landscape',false);setTimeout(()=>finalizeLandscapeReturn(true),180)};
$('#tryLandscapeBtn').onclick=()=>{tryOrientation('landscape',true);updateOrientationBanner()};
function addMuddle(){const now=performance.now();if(now-state.lastMuddle<55)return;state.lastMuddle=now;state.muddleProgress=Math.min(100,state.muddleProgress+7);$('#muddleGlass').classList.add('hit');setTimeout(()=>$('#muddleGlass').classList.remove('hit'),90);updateMuddle();if(state.muddleProgress>=100)finishPhysical('Perfekt. Myntan är varsamt muddlad.')}
$('#muddleGlass').onpointerdown=e=>{e.preventDefault();addMuddle()};$('#muddleGlass').onpointermove=e=>{if(e.buttons||e.pointerType==='touch'){e.preventDefault();addMuddle()}};$('#muddleFallback').onclick=()=>{state.muddleProgress=Math.min(100,state.muddleProgress+18);updateMuddle();if(state.muddleProgress>=100)finishPhysical('Perfekt. Myntan är varsamt muddlad.')};
function updateMuddle(){$('#muddleFill').style.width=state.muddleProgress+'%';$('#muddleStatus').textContent=Math.round(state.muddleProgress)+'%'}
window.addEventListener('devicemotion',e=>{if(state.action!=='shake'||$('#shakeStage').classList.contains('hidden'))return;const a=e.accelerationIncludingGravity||e.acceleration;if(!a)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2),now=performance.now();if(mag>15&&now-state.lastMotion>95){state.lastMotion=now;state.shakeProgress=Math.min(100,state.shakeProgress+7);updateShake();if(state.shakeProgress>=100)finishPhysical('Där satt den. Bra skakat!')}});
$('#shakeFallback').onclick=()=>{state.shakeProgress=Math.min(100,state.shakeProgress+18);updateShake();if(state.shakeProgress>=100)finishPhysical('Där satt den. Bra skakat!')};function updateShake(){$('#shakeFill').style.width=state.shakeProgress+'%';$('#shakeStatus').textContent=Math.round(state.shakeProgress)+'%'}
window.addEventListener('deviceorientation',e=>{if(state.action!=='drink'||$('#drinkStage').classList.contains('hidden'))return;if(state.baselineBeta===null){state.baselineBeta=e.beta||0;state.baselineGamma=e.gamma||0;return}const db=Math.abs((e.beta||0)-state.baselineBeta),dg=Math.abs((e.gamma||0)-state.baselineGamma),tilt=Math.max(db,dg);state.drinkProgress=Math.max(state.drinkProgress,Math.min(100,(tilt-8)/58*100));updateDrink();if(state.drinkProgress>=98)finishPhysical('Glaset är tomt. Inte illa!')});
$('#drinkFallback').onclick=()=>{state.drinkProgress=Math.min(100,state.drinkProgress+20);updateDrink();if(state.drinkProgress>=100)finishPhysical('Glaset är tomt. Inte illa!')};function updateDrink(){const p=Math.max(0,Math.min(100,state.drinkProgress));$('#drinkFill').style.width=p+'%';$('#liquid').style.height=(78*(1-p/100))+'%';$('#drinkStatus').textContent=p<20?'Glaset är fullt.':p<70?'Du dricker…':p<98?'Nästan tomt…':'Tomt!'}
function showResult(){show('resultScreen');const max=state.drink.steps.length*10,accuracy=state.correct/(state.correct+state.wrong||1),time=Math.round((Date.now()-state.startedAt)/1000),score=Math.max(0,Math.min(100,Math.round((state.points/max)*75+accuracy*25)));$('#scoreValue').textContent=score;$('#resultTitle').textContent=`${state.drink.name} klar!`;$('#resultLine').textContent=score>=90?'Bartendern nickar imponerat.':score>=70?'Bra jobbat – den hade kunnat serveras.':'Du tog dig igenom drinken. Nästa blir bättre.';$('#scoreGrid').innerHTML=`<div><b>${state.correct}</b><br><small>rätt</small></div><div><b>${state.wrong}</b><br><small>fel</small></div><div><b>${time}s</b><br><small>tid</small></div>`;speak($('#resultLine').textContent)}
$('#anotherBtn').onclick=()=>{state.phase='chat';state.drink=null;state.serving=null;updateHud();show('barScreen');const t='En till? Absolut. Vad är du sugen på nu?';$('#dialogText').textContent=t;speak(t,()=>renderConversationInput())};$('#changeMoodBtn').onclick=()=>{state.phase='mood';state.drink=null;show('moodScreen');speak(`Vilket mood är du på nu, ${state.name}?`)};
function recognize(onResult,button,status){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){if(status)status.textContent='Taligenkänning stöds inte här.';else toast('Taligenkänning stöds inte i den här webbläsaren.');return}try{stopSpeech();const r=new SR();r.lang='sv-SE';r.interimResults=false;r.maxAlternatives=3;const old=button?.textContent||'';r.onstart=()=>{if(button){button.textContent='🎙️ Lyssnar…';button.disabled=true}if(status)status.textContent='Jag lyssnar…';else toast('Jag lyssnar…')};r.onerror=()=>{if(status)status.textContent='Jag hörde inte tydligt. Försök igen.';else toast('Jag hörde inte. Försök igen.')};r.onend=()=>{if(button&&document.body.contains(button)){button.textContent=old;button.disabled=false}};r.onresult=e=>{const a=[];for(let i=0;i<e.results[0].length;i++)a.push(e.results[0][i].transcript);onResult(a)};r.start()}catch(e){toast('Mikrofonen kunde inte startas.')}}
function handleOrientation(){setTimeout(()=>{updateOrientationBanner();if(state.waitingPortrait&&isPortrait()&&$('#actionScreen').classList.contains('active'))showPhysicalStage();if(state.waitingLandscape&&isLandscape()&&$('#actionScreen').classList.contains('active'))finalizeLandscapeReturn()},160)}
window.addEventListener('orientationchange',handleOrientation);window.addEventListener('resize',handleOrientation);const mq=matchMedia('(orientation: portrait)');if(mq.addEventListener)mq.addEventListener('change',handleOrientation);else mq.addListener?.(handleOrientation);updateOrientationBanner();
})();
