$$('.difficultyBtn').forEach(btn=>btn.onclick=()=>{state.difficulty=btn.dataset.difficulty;$$('.difficultyBtn').forEach(b=>b.classList.toggle('selected',b===btn));$('#difficultyHelp').textContent=state.difficulty==='easy'?'Lätt: välj mellan tre alternativ eller säg svaret.':state.difficulty==='medium'?'Medel: kärnan i svaret räcker. Skriv eller prata. Efter tre fel får du tre tips.':'Svår: samma som Medel, plus mängder och proportioner. Efter tre fel får du tre tips.'});
$('#sensorBtn').onclick=requestSensors;
$('#enterBtn').onclick=()=>{const name=$('#nameInput').value.trim(),age=Number($('#ageInput').value);if(!name||!age||age<1||age>120){$('#startError').textContent='Fyll i namn och en rimlig ålder.';return}state.name=name;state.age=age;state.under18=age<18;state.phase='mood';$('#startError').textContent='';$('#moodHello').textContent=`Hej ${name}! Välkommen.`;$('#moodPrompt').textContent=state.under18?'Vilket mood är du på idag? Jag håller baren helt alkoholfri.':'Vilket mood är du på idag?';show('moodScreen');speak(`Hej ${name}! Välkommen. Vilket mood är du på idag?`)};
$$('.mood').forEach(btn=>btn.onclick=()=>selectMood(btn.dataset.mood));
function selectMood(mood){if(state.phase!=='mood')return;state.phase='chat';state.mood=mood;state.bar=mood==='surprise'?['tropical','manhattan','rooftop','hotel'][Math.floor(Math.random()*4)]:moodToBar[mood];$$('.mood').forEach(b=>b.disabled=true);speak(moodLines[mood]);enterBar();tryOrientation('landscape',true);setTimeout(()=>$$('.mood').forEach(b=>b.disabled=false),1200)}
function enterBar(){stopIdle();makeBottles();$('#barScene').className=state.bar;state.conversationIndex=0;state.conversationAnswers={};state.drink=null;state.serving=null;updateHud();show('barScreen');updateOrientationBanner();const intro=`Välkommen till min ${barName(state.bar)}, ${state.name}. Slå dig ner.`;$('#dialogText').textContent=intro;$('#dialogControls').innerHTML='';speak(intro,()=>renderConversationInput())}
function renderConversationInput(){if(state.phase!=='chat')return;const q=convo[Math.min(state.conversationIndex,convo.length-1)]?.q(state.name)||'Vad är du sugen på?';const t=state.conversationIndex<convo.length?q:pick(['Vad känner du för nu då?','Ska vi blanda något åt dig?','Nå, har du landat i vad du är sugen på?']);$('#dialogText').textContent=t;speak(t);$('#dialogControls').innerHTML=`<div class="inputRow"><input id="chatInput" placeholder="Svara, fråga eller beställ"><button class="btn" id="chatSendBtn">Säg</button><button class="btn secondary" id="chatMicBtn">🎙️</button></div><div class="small">Samtalet och beställningen är samma flöde.</div>`;$('#chatSendBtn').onclick=()=>handleConversation($('#chatInput').value);$('#chatInput').onkeydown=e=>{if(e.key==='Enter')handleConversation(e.target.value)};$('#chatMicBtn').onclick=()=>recognize(alts=>handleConversation(alts[0]||''),$('#chatMicBtn'));scheduleIdle()}
function resolveDrink(q){const x=normalize(q),aliases={'mojito':'mojito','mohito':'mojito','margarita':'margarita','manhattan':'manhattan','virgin mojito':'virgin_mojito','alkoholfri mojito':'virgin_mojito','mocktail mojito':'virgin_mojito','shirley temple':'shirley','tropical cooler':'tropical_cooler','tropisk drink':'tropical_cooler'};let id=aliases[x];if(!id)for(const[k,v]of Object.entries(aliases)){if(x.includes(k)){id=v;break}}return drinks.find(d=>d.id===id)}
function handleConversation(raw){stopIdle();const text=String(raw||'').trim();if(!text){toast('Säg eller skriv något först.');return}const drink=resolveDrink(text);if(drink){orderDrink(drink);return}const item=convo[Math.min(state.conversationIndex,convo.length-1)];if(isRepeatRequest(text)){const q=state.conversationIndex<convo.length?item.q(state.name):'Vad är du sugen på?';const r=`Absolut. Jag frågade: ${q}`;$('#dialogText').textContent=r;speak(r);return}const askedMe=answerBartenderQuestion(normalize(text));if(item&&state.conversationIndex<convo.length)state.conversationAnswers[item.key]=text;const reply=askedMe?`${naturalConversationReaction(text)} ${askedMe}`:naturalConversationReaction(text);if(state.conversationIndex<convo.length)state.conversationIndex++;$('#dialogControls').innerHTML='';$('#dialogText').textContent=reply;speak(reply,()=>setTimeout(()=>{if(state.phase==='chat')renderConversationInput()},650))}
function naturalConversationReaction(text){const x=normalize(text);if(/bra|fint|toppen|kanon|perfekt|helt okej/.test(x))return pick(['Skönt att höra.','Härligt.','Bra, det gillar jag att höra.']);if(/daligt|jobbigt|trott|stress|sliten|inte bra/.test(x))return pick(['Då hoppas jag att det lugnar sig lite här inne.','Jag fattar. Vi tar det lugnt.','Då får baren bli en liten paus.']);if(/jobbar|arbete|jobb/.test(x))return pick(['Ja, då är det skönt att släppa jobbet en stund.','Det låter som att du förtjänar lite barhäng.']);if(/pension/.test(x))return pick(['Det låter ändå som att du kan styra lite mer över tiden.','Inte dumt att äga lite mer av sin egen kalender.']);if(/studer|pluggar|skola/.test(x))return pick(['Då har du säkert nog att hålla reda på redan.','Plugget tar sin tid, det hör jag ofta här.']);return pick(['Jag fattar.','Mm, jag hör dig.','Jaså, där ser man.','Okej, det köper jag.'])}
function orderDrink(d){stopIdle();if(state.under18&&d.minAge>=18){const t='Den innehåller alkohol. Jag kan göra en Virgin Mojito, Shirley Temple eller Tropical Cooler istället.';$('#dialogText').textContent=t;speak(t,()=>renderConversationInput());return}state.phase='recipe';state.drink=d;state.step=0;state.correct=0;state.wrong=0;state.points=0;state.startedAt=Date.now();state.serving=null;state.questionFails=0;state.amountFails=0;state.lastRecipeQuestion='';updateHud();$('#dialogControls').innerHTML='';const intro=pick([`${d.intro} Bra val. Du får hjälpa mig bakom baren.`,`${d.intro} Då kör vi. Jag tänker att du får jobba lite också.`,`${d.intro} Snyggt val. Kom, så bygger vi den tillsammans.`]);$('#dialogText').textContent=intro;speak(intro,()=>{if(state.difficulty==='hard')askServing();else renderStep(true)})}
function parseNum(text){const x=normalize(text).replace(',','.');const words={en:1,ett:1,tva:2,tre:3,fyra:4,fyran:4,fem:5,sex:6,sexa:6,sexan:6,sju:7,atta:8,attan:8,nio:9,tio:10,tolv:12,sexton:16};for(const[w,n]of Object.entries(words))if(x===w||x.includes(w))return n;const m=x.match(/\d+(?:\.\d+)?/);return m?Number(m[0]):NaN}
function naturalQuestion(s){const q=normalize(s.q);let variants=[];if(/orts|ort/.test(q)||/ort/.test(q))variants=[];if(/bassprit|grunden/.test(q))variants=['Vi börjar med själva grunden. Vilken bassprit tar vi?','Okej, först basen. Vad häller vi i som bassprit?',`Nu sätter vi fundamentet. ${s.q}`];else if(/citrus/.test(q))variants=['Nu behöver vi syra. Vilken citrus ska i?','Bra, då tar vi nästa smak. Vilken citrus plockar vi fram?',`Vi har kommit en bit. ${s.q}`];else if(/ort|ört/.test(s.q.toLowerCase()))variants=['Nu har vi kommit så långt. Vilken ört ska vi ha i?','Dags för det gröna. Vilken ört hör hemma här?','Bra. Vad plockar vi fram för ört nu?'];else if(/sotma|sötma/.test(s.q.toLowerCase()))variants=['Nu behöver vi balansera syran. Vad använder vi för sötma?','Okej, lite sötma också. Vad tar vi?'];else if(/glas/.test(q))variants=['Nu ska den få rätt hem. Vilket glas väljer du?','Bra, drinken börjar sitta. Vilket glas passar bäst?',s.q];else if(/garnish|dekor/.test(q))variants=['Sista touchen nu. Vad garnerar vi med?','Nu ska den se färdig ut också. Vad lägger vi på som garnish?',s.q];else if(/kyla|kylas|blandar|behandlar/.test(q))variants=[`Nu har vi ingredienserna på plats. ${s.q}`,'Okej, vad gör vi med det här nu?',s.q];else if(/toppar/.test(q))variants=['Nästan där. Vad toppar vi med?','Nu återstår toppen. Vad ska i?',s.q];else variants=[s.q,`Bra, nästa steg. ${s.q}`,`Okej, då går vi vidare. ${s.q}`];return pick(variants)}
function renderStep(newStep=false){if(state.step>=state.drink.steps.length){startPhysicalAction('drink','result');return}if(newStep){state.questionFails=0;state.amountFails=0}const s=state.drink.steps[state.step];state.lastRecipeQuestion=naturalQuestion(s);$('#dialogText').textContent=state.lastRecipeQuestion;speak(state.lastRecipeQuestion);if(state.difficulty==='easy')renderEasy(s);else renderFree(s)}
function recipeInputHTML(placeholder){return `<div class="freeAnswerRow"><input id="recipeText" placeholder="${placeholder}"><button class="btn" id="recipeSend">Svara</button><button class="btn secondary" id="recipeMic">🎙️</button><div class="recipeTalkNote">Du kan prata fritt med bartendern. Receptfrågan väntar tills du faktiskt svarar.</div><div class="freeAnswerStatus" id="recipeStatus"></div></div>`}
function renderEasy(s){$('#dialogControls').innerHTML=`<div class="choices">${s.opts.map(o=>`<button class="choice">${o}</button>`).join('')}</div>${recipeInputHTML('Skriv svar eller prata med bartendern')}`;$$('.choice').forEach(b=>b.onclick=()=>answerStep(b.textContent,b));wireRecipeInput()}
function renderFree(s,message=''){const hint=state.questionFails>=3?`<div class="hintTitle">Tre fel – här får du tre alternativ. Ett är rätt.</div><div class="choices">${s.opts.map(o=>`<button class="choice">${o}</button>`).join('')}</div>`:'';$('#dialogControls').innerHTML=`${recipeInputHTML('Skriv svaret själv eller prata')}${hint}`;const st=$('#recipeStatus');if(st)st.textContent=message||'Inga svarsalternativ visas.';$$('.choice').forEach(b=>b.onclick=()=>answerStep(b.textContent,b));wireRecipeInput()}
function wireRecipeInput(){const input=$('#recipeText'),send=$('#recipeSend'),mic=$('#recipeMic');if(send&&input)send.onclick=()=>handleRecipeInput(input.value);if(input)input.onkeydown=e=>{if(e.key==='Enter')handleRecipeInput(e.target.value)};if(mic)mic.onclick=()=>recognize(alts=>handleRecipeInput(alts[0]||''),mic,$('#recipeStatus'))}
function handleRecipeInput(raw){
  const text=String(raw||'').trim(),s=state.drink?.steps[state.step];if(!s||state.phase!=='recipe')return;
  if(!text){toast('Säg eller skriv något först.');return}
  const input=$('#recipeText');if(input)input.value='';
  if(isRepeatRequest(text)){state.recipeChatTurns=0;const r=`Absolut. Frågan var: ${state.lastRecipeQuestion||s.q}`;$('#dialogText').textContent=r;speak(r);return}
  if(correctForDifficulty(text,s)){state.recipeChatTurns=0;answerStep(s.a,null,true);return}
  const wrong=wrongOptionForStep(text,s);
  if(wrong||explicitAnswerIntent(text)){state.recipeChatTurns=0;registerWrongAnswer(s);return}
  state.recipeChatTurns++;
  let reply=smallTalkReply(text);
  if(state.recipeChatTurns>=4){reply+=' '+bridgeBackToQuestion(state.lastRecipeQuestion||s.q);state.recipeChatTurns=0}
  $('#dialogText').textContent=reply;speak(reply)
}
function registerWrongAnswer(s){state.wrong++;state.points=Math.max(0,state.points-2);state.questionFails++;const msg=state.difficulty!=='easy'&&state.questionFails>=3?'Inte riktigt. Du har tre missar nu, så jag ger dig tre alternativ. Ett är rätt.':pick(['Inte riktigt. Försök en gång till.','Nja, inte den. Ta ett nytt försök.','Nästan kanske, men inte rätt. Försök igen.']);$('#dialogText').textContent=msg;speak(msg,()=>{if(state.difficulty==='easy')renderEasy(s);else renderFree(s,msg)})}
async function answerStep(answer,btn,alreadyValidated=false){
  const s=state.drink.steps[state.step];
  const ok=alreadyValidated || (btn ? normalize(answer)===normalize(s.a) : correctForDifficulty(answer,s));
  if(!ok){if(btn)btn.classList.add('bad');registerWrongAnswer(s);return}
  state.correct++;state.points+=10;state.recipeChatTurns=0;if(btn)btn.classList.add('good');
  if(state.difficulty==='hard'&&s.amount){askAmount(s);return}
  const praise=pick(['Precis.','Rätt, där satt den.','Snyggt.','Ja, exakt så.','Bra. Nu börjar det likna något.','Korrekt. Vidare!']);$('#dialogText').textContent=praise;speak(praise,()=>advanceStep(s))
}
function expectedAmount(s){return s.amount.base*((state.serving||4)/4)}
function fmt(n,u){const v=Number.isInteger(n)?String(n):String(Math.round(n*10)/10).replace('.',',');return `${v} ${u}`}
function promptTalkOrRepeat(value,prompt,status){if(isRepeatRequest(value)){status.textContent='Jag tar frågan igen.';speak(`Absolut. ${prompt}`);return true}const x=String(value||'').trim();if(!x)return false;const n=parseNum(x);if(!Number.isFinite(n)&&looksLikeSmallTalk(x,null)){const reply=smallTalkReply(x);status.textContent=reply;speak(reply);return true}return false}
function askServing(){const d=state.drink,prompt=d.alcoholic?`${d.name}. På svår nivå: vill du göra en fyra, sexa eller åtta?`:`${d.name}. På svår nivå: vill du göra en liten, mellan eller stor?`;showPrompt('Bartendern',prompt,d.alcoholic?'4, 6 eller 8':'liten, mellan eller stor',(value,status,wrap)=>{if(promptTalkOrRepeat(value,prompt,status))return;let n;if(!d.alcoholic){const x=normalize(value);if(x.includes('liten'))n=4;else if(x.includes('mellan'))n=6;else if(x.includes('stor'))n=8}if(!n)n=parseNum(value);if(![4,6,8].includes(n)){status.textContent=d.alcoholic?'Svara 4, 6 eller 8.':'Svara liten, mellan eller stor.';return}state.serving=n;updateHud();wrap.remove();const r=d.alcoholic?pick([`${n}:a. Då skalar vi receptet efter den.`,`${n}:a blir bra. Då räknar vi därefter.`]):`Bra, då kör vi ${n===4?'liten':n===6?'mellan':'stor'}.`;$('#dialogText').textContent=r;speak(r,()=>renderStep(true))})}
function showPrompt(title,text,placeholder,onSubmit){document.querySelector('.hardPromptOverlay')?.remove();const wrap=document.createElement('div');wrap.className='hardPromptOverlay';wrap.innerHTML=`<div class="hardPromptCard"><h3>${title}</h3><p>${text}</p><div class="hardPromptRow"><input id="hardPromptInput" placeholder="${placeholder}"><button class="btn" id="hardPromptSend">Svara</button><button class="btn secondary" id="hardPromptMic">🎙️</button></div><div class="recipeTalkNote">Kallprat och “upprepa frågan” fungerar även här.</div><div id="hardPromptStatus" class="hardPromptStatus"></div><div id="amountHints"></div></div>`;document.body.appendChild(wrap);const input=$('#hardPromptInput'),send=$('#hardPromptSend'),mic=$('#hardPromptMic'),status=$('#hardPromptStatus');send.onclick=()=>onSubmit(input.value,status,wrap);input.onkeydown=e=>{if(e.key==='Enter')onSubmit(input.value,status,wrap)};mic.onclick=()=>recognize(alts=>{input.value=alts[0]||'';onSubmit(input.value,status,wrap)},mic,status);speak(text);return wrap}
function askAmount(s){state.amountFails=0;const expected=expectedAmount(s),size=state.drink.alcoholic?`${state.serving}:an`:state.serving===4?'den lilla':state.serving===6?'mellanstorleken':'den stora';const prompt=pick([`Bra, ${s.a}. Hur mycket ${s.amount.label} ska vi ha till ${size}?`,`Okej, ${s.a} är rätt. Nu mängden: hur mycket ${s.amount.label} till ${size}?`,`Ingrediensen sitter. Hur mycket ${s.amount.label} mäter du upp till ${size}?`]);showPrompt('Bartendern',prompt,`Mängd i ${s.amount.unit}`,(value,status,wrap)=>{if(promptTalkOrRepeat(value,prompt,status))return;const n=parseNum(value);if(Number.isFinite(n)&&Math.abs(n-expected)<.11){status.textContent=`Rätt: ${fmt(expected,s.amount.unit)}.`;speak(pick([`Precis. ${fmt(expected,s.amount.unit)}.`,`Japp, ${fmt(expected,s.amount.unit)} blir rätt.`]),()=>{wrap.remove();advanceStep(s)});return}state.wrong++;state.points=Math.max(0,state.points-2);state.amountFails++;status.textContent=state.amountFails>=3?'Tre fel. Här får du tre alternativ – ett är rätt.':`Inte riktigt. Försök igen. (${state.amountFails}/3)`;speak('Inte riktigt. Tänk på proportionerna.');if(state.amountFails>=3)renderAmountHints(expected,s.amount.unit,status,wrap,s)})}
function renderAmountHints(expected,unit,status,wrap,s){const box=wrap.querySelector('#amountHints');if(!box||box.children.length)return;const vals=[expected,Math.max(.5,expected*.5),expected*1.5].map(n=>Math.round(n*10)/10).sort(()=>Math.random()-.5);box.innerHTML=`<div class="hintTitle">Tre alternativ – ett är rätt.</div><div class="amountHints">${vals.map(v=>`<button class="choice" data-v="${v}">${fmt(v,unit)}</button>`).join('')}</div>`;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.v);if(Math.abs(v-expected)<.11){b.classList.add('good');status.textContent='Rätt.';speak(`Precis. ${fmt(expected,unit)}.`,()=>{wrap.remove();advanceStep(s)})}else{b.classList.add('bad');state.wrong++;state.points=Math.max(0,state.points-2);status.textContent='Inte den. Ett av de andra två är rätt.'}})}
function advanceStep(s){state.step++;state.questionFails=0;state.amountFails=0;state.lastRecipeQuestion='';if(s.action)startPhysicalAction(s.action,'continue');else renderStep(true)}
