(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const M={difficulty:'easy',drink:'',serving:null,sizePrompted:''};
const help={easy:'Lätt: välj mellan tre alternativ eller säg svaret.',medium:'Medel: inga svarsalternativ visas. Skriv eller säg svaret själv.',hard:'Svår: inga svarsalternativ visas. Du måste också kunna mängderna i receptet.'};
const recipes={
'Mojito':{alcoholic:true,a:[['Vilken bassprit börjar vi med?','Vit rom','vit rom',4,'cl'],['Vilken citrus ska i?','Lime','limejuice',2,'cl'],['Vilken ört hör hemma i en Mojito?','Mynta','mynta',8,'blad'],['Vad använder vi för sötma?','Socker','socker',2,'tsk'],['Vad toppar vi med?','Sodavatten','sodavatten',4,'cl']]},
'Margarita':{alcoholic:true,a:[['Vilken bassprit börjar vi med?','Tequila','tequila',4,'cl'],['Vilken citrus ska i?','Lime','limejuice',2,'cl'],['Vilken apelsinlikör används ofta?','Triple sec','triple sec',2,'cl']]},
'Manhattan':{alcoholic:true,a:[['Vilken bassprit är grunden?','Whisky','whisky',4,'cl'],['Vilken förstärkt vin-ingrediens används?','Söt vermouth','söt vermouth',2,'cl'],['Vilken bitter används ofta?','Angostura bitters','Angostura bitters',2,'stänk']]},
'Virgin Mojito':{alcoholic:false,a:[['Vilken citrus börjar vi med?','Lime','limejuice',2,'cl'],['Vilken ört använder vi?','Mynta','mynta',8,'blad'],['Vad använder vi för sötma?','Sockerlag','sockerlag',2,'cl'],['Vad toppar vi med?','Sodavatten','sodavatten',8,'cl']]},
'Shirley Temple':{alcoholic:false,a:[['Vilken bas använder vi?','Ginger ale','ginger ale',12,'cl'],['Vilken söt röd ingrediens ska i?','Grenadin','grenadin',2,'cl'],['Vilken citrus passar?','Lime eller citron','citrusjuice',1,'cl']]},
'Tropical Cooler':{alcoholic:false,a:[['Vilken juice ger tropisk bas?','Ananasjuice','ananasjuice',6,'cl'],['Vilken citrus ger syra?','Lime','limejuice',2,'cl'],['Vilken andra juice passar?','Apelsinjuice','apelsinjuice',6,'cl']]}
};
function norm(t){return String(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9,. ]/g,' ').replace(/\s+/g,' ').trim().replace(/whiskey/g,'whisky').replace(/high ball/g,'highball').replace(/martini glas/g,'martiniglas').replace(/cocktail glas/g,'cocktailglas').replace(/margarita glas/g,'margaritaglas').replace(/soda vatten/g,'sodavatten').replace(/trippel sek|trippelsek/g,'triple sec')}
function alias(t){let x=norm(t);const A=[[/^rom$/,'vit rom'],[/^soda$/,'sodavatten'],[/^highball$/,'highballglas'],[/^martini$/,'martiniglas'],[/^cocktail$/,'cocktailglas'],[/^salt$/,'saltkant'],[/^muddla$/,'muddla forsiktigt'],[/^ror$|^rora$|^rora med is$/,'ror med is'],[/^lime mynta$|^lime och mynta$/,'lime och mynta'],[/^lime citron$|^lime eller citron$/,'lime eller citron'],[/^apelsin lime$|^apelsin eller lime$/,'apelsin eller lime']];for(const [r,v] of A)if(r.test(x))return v;return x}
function score(h,o){h=alias(h);o=norm(o);if(!h||!o)return 0;if(h===o)return 100;if(o.includes(h)||h.includes(o))return 90;const H=new Set(h.split(' ')),O=new Set(o.split(' '));let c=0;H.forEach(x=>O.has(x)&&c++);return c?70*c/Math.max(1,Math.min(H.size,O.size)):0}
function best(t,buttons){let b=null,s=0;for(const x of buttons){const n=score(t,x.textContent);if(n>s){s=n;b=x}}return s>=55?b:null}
function speak(t){try{if(!speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='sv-SE';u.rate=.97;speechSynthesis.speak(u)}catch(e){}}
function rec(cb,btn,status){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status.textContent='Taligenkänning stöds inte i den här webbläsaren.';return}try{speechSynthesis?.cancel();const r=new SR();r.lang='sv-SE';r.interimResults=false;r.maxAlternatives=3;const old=btn.textContent;r.onstart=()=>{btn.textContent='🎙️ Lyssnar…';btn.disabled=true;status.textContent='Jag lyssnar…'};r.onend=()=>{if(document.body.contains(btn)){btn.textContent=old;btn.disabled=false}};r.onerror=e=>status.textContent=e.error==='not-allowed'?'Mikrofonen är blockerad.':'Jag hörde inte tydligt. Försök igen.';r.onresult=e=>{const a=[];for(let i=0;i<e.results[0].length;i++)a.push(e.results[0][i].transcript);cb(a)};r.start()}catch(e){status.textContent='Mikrofonen kunde inte startas.'}}
$$('.difficultyBtn').forEach(b=>b.onclick=()=>{M.difficulty=b.dataset.difficulty;$$('.difficultyBtn').forEach(x=>x.classList.toggle('selected',x===b));$('#difficultyHelp').textContent=help[M.difficulty];try{sessionStorage.setItem('barDifficulty',M.difficulty)}catch(e){}});
try{const s=sessionStorage.getItem('barDifficulty');if(['easy','medium','hard'].includes(s)){M.difficulty=s;$$('.difficultyBtn').forEach(x=>x.classList.toggle('selected',x.dataset.difficulty===s));$('#difficultyHelp').textContent=help[s]}}catch(e){}
function label(){return M.difficulty==='easy'?'Lätt':M.difficulty==='medium'?'Medel':'Svår'}
function hud(){const h=$('#hudPlayer');if(!h||!h.textContent||h.textContent==='Spelare')return;const base=h.textContent.replace(/ · (Lätt|Medel|Svår)( · [468]:a)?$/,'');const sz=M.difficulty==='hard'&&M.serving&&recipes[M.drink]?.alcoholic?` · ${M.serving}:a`:'';const next=`${base} · ${label()}${sz}`;if(h.textContent!==next)h.textContent=next}
function easyVoice(c,choices){if(c.querySelector('#answerMic15'))return;const row=document.createElement('div');row.className='freeAnswerRow';row.style.marginTop='10px';const b=document.createElement('button');b.id='answerMic15';b.className='btn secondary';b.textContent='🎙️ Säg svaret';const st=document.createElement('span');st.className='freeAnswerStatus';st.textContent='Tryck på ett alternativ eller säg svaret.';b.onclick=()=>rec(alts=>{let m=null,heard=alts[0]||'';for(const a of alts){m=best(a,choices);if(m){heard=a;break}}if(m){st.textContent=`Jag hörde: “${heard}” → ${m.textContent}`;setTimeout(()=>m.click(),250)}else st.textContent=`Jag hörde: “${heard}”, men kunde inte koppla det till något svar.`},b,st);row.append(b,st);c.append(row)}
function parseNum(t){let x=norm(t).replace(',','.');const W={en:1,ett:1,tva:2,tre:3,fyra:4,fyran:4,fem:5,sex:6,sexa:6,sexan:6,sju:7,atta:8,attan:8,nio:9,nian:9,tio:10,tolv:12,sexton:16};if(W[x]!=null)return W[x];for(const [w,n] of Object.entries(W))if(x.includes(w))return n;const m=x.match(/\d+(?:\.\d+)?/);return m?+m[0]:NaN}
function fmt(n,u){const v=Number.isInteger(n)?n:String(Math.round(n*10)/10).replace('.',',');return `${v} ${u}`}
function overlay(text,placeholder,submit){document.querySelector('.hardPromptOverlay')?.remove();const w=document.createElement('div');w.className='hardPromptOverlay';w.innerHTML=`<div class="hardPromptCard"><h3>Bartendern</h3><p>${text}</p><div class="hardPromptRow"><input id="hpIn" placeholder="${placeholder}"><button class="btn" id="hpSend">Svara</button><button class="btn secondary" id="hpMic">🎙️</button></div><div class="hardPromptStatus" id="hpStatus"></div></div>`;document.body.append(w);const i=$('#hpIn'),s=$('#hpSend'),m=$('#hpMic'),st=$('#hpStatus');const go=()=>submit(i.value,st,w);s.onclick=go;i.onkeydown=e=>e.key==='Enter'&&go();m.onclick=()=>rec(a=>{i.value=a[0]||'';submit(i.value,st,w)},m,st);setTimeout(()=>i.focus(),100)}
function ensureSize(){if(M.difficulty!=='hard')return;const d=$('#hudDrink')?.textContent.trim();if(!recipes[d])return;if(M.drink!==d){M.drink=d;M.serving=null;M.sizePrompted=''}if(M.serving||M.sizePrompted===d)return;M.sizePrompted=d;const r=recipes[d];const text=r.alcoholic?`${d}. Vill du ha en fyra, sexa eller åtta? Skriv eller säg 4, 6 eller 8.`:`${d}. Vill du göra en liten, mellan eller stor?`;speak(text);overlay(text,r.alcoholic?'4, 6 eller 8':'liten, mellan eller stor',(v,st,w)=>{let n,x=norm(v);if(!r.alcoholic){if(x.includes('liten'))n=4;else if(x.includes('mellan'))n=6;else if(x.includes('stor'))n=8}if(!n)n=parseNum(v);if(![4,6,8].includes(n)){st.textContent=r.alcoholic?'Svara 4, 6 eller 8.':'Svara liten, mellan eller stor.';return}M.serving=n;hud();w.remove();speak(r.alcoholic?`${n}:a. Då skalar vi resten av receptet efter det.`:'Bra, då har vi storleken.')})}
function specFor(q,answer){const r=recipes[M.drink];if(!r)return null;return r.a.find(x=>norm(q).startsWith(norm(x[0]))&&norm(answer)===norm(x[1]))||null}
function askAmount(sp,button,status){const expected=sp[3]*(M.serving||4)/4,unit=sp[4],size=recipes[M.drink]?.alcoholic?`${M.serving}:an`:M.serving===4?'den lilla':M.serving===6?'mellanstorleken':'den stora';const text=`Bra, ${button.textContent}. Hur mycket ${sp[2]} ska vi ha till ${size}?`;speak(text);overlay(text,`Mängd i ${unit}`,(v,st,w)=>{const n=parseNum(v);if(!Number.isFinite(n)||Math.abs(n-expected)>.11){st.textContent='Inte riktigt. Försök igen.';speak('Inte riktigt. Försök igen.');return}status.textContent=`Rätt mängd: ${fmt(expected,unit)}.`;speak(`Precis. ${fmt(expected,unit)}.`);setTimeout(()=>{w.remove();button.click()},500)})}
function free(c,choices){if(c.querySelector('#free15'))return;choices.style.display='none';choices.dataset.q15=$('#dialogText')?.textContent||'';const row=document.createElement('div');row.id='free15';row.className='freeAnswerRow';const i=document.createElement('input');i.placeholder='Skriv svaret själv';const s=document.createElement('button');s.className='btn';s.textContent='Svara';const m=document.createElement('button');m.className='btn secondary';m.textContent='🎙️';const st=document.createElement('div');st.className='freeAnswerStatus';st.textContent=M.difficulty==='hard'?'Svår: inga alternativ visas.':'Medel: inga alternativ visas.';const go=t=>{const b=best(t,[...choices.querySelectorAll('.choice')]);if(!b){st.textContent=`Jag känner inte igen “${t}” som svar.`;return}st.textContent=`Jag tolkar svaret som: ${b.textContent}.`;if(M.difficulty==='hard'){ensureSize();if(!M.serving){st.textContent='Välj först storlek/styrka.';return}const sp=specFor(choices.dataset.q15||$('#dialogText').textContent,b.textContent);if(sp){askAmount(sp,b,st);return}}setTimeout(()=>b.click(),180)};s.onclick=()=>go(i.value);i.onkeydown=e=>e.key==='Enter'&&go(i.value);m.onclick=()=>rec(a=>{i.value=a[0]||'';go(i.value)},m,st);row.append(i,s,m,st);c.append(row)}
function enhance(){hud();const c=$('#dialogControls'),choices=c?.querySelector('.choices');if(!choices)return;if(!choices.dataset.q15)choices.dataset.q15=$('#dialogText')?.textContent||'';if(M.difficulty==='easy'){choices.style.display='grid';easyVoice(c,[...choices.querySelectorAll('.choice')])}else{free(c,choices);if(M.difficulty==='hard')ensureSize()}}
const c=$('#dialogControls');if(c)new MutationObserver(()=>setTimeout(enhance,0)).observe(c,{childList:true,subtree:true});const d=$('#hudDrink');if(d)new MutationObserver(()=>{const n=d.textContent.trim();if(n!==M.drink){M.drink=n;M.serving=null;M.sizePrompted=''}setTimeout(enhance,40)}).observe(d,{childList:true,characterData:true,subtree:true});setInterval(enhance,900);setTimeout(enhance,350);
})();